export default {
    home: 'Home',
    nav_tournament: "Leagues",
    nav_team: 'Team',
    nav_pricing: "Price list",
    nav_blog: "Blog",
    nav_shopping: "Shops",
    nav_login: "Login",
    nav_register: "Register",
    nav_create_tournament: "Create league",
    nav_find_tournament: "Find league",
    nav_create_team: "Create team",
    nav_find_team: "Find team",
    nav_create_lineup: "Create lineup",
    vn: "Vietnamese",
    gb: "England",
    nav_account_information: "Account information",
    nav_account_my_leagues: "My leagues",
    nav_account_my_teams: "My teams",
    nav_account_my_orders: "My orders",
    nav_account_logout: "Log out",
    notifications: "Notifications",
    make_tournament_system: "Make Tournamation System",
    terms_of_user: "Terms of user",
    privacy_policy: "Privacy policy",
    payment_policy: "Payment policy",
    contact: "Contact",
    information_security_policy: "Information security policy",
    comments_on_football_legend: "Comments on Football-Legend",
    company_name: "Football-Legend.,JSC",
    license: "© 2023 - Copyright by football-legend.vn\nCopyright",
    community_page: "Football-Legend community",
    facebook_group: `Facebook group`,
    members: "members",
    visit_group: "Visit group",
    facebook_introduction: "Please join our Facebook group for the best support.",
    setup_league: "Setup league",
    operate_league: "Operate league",
    create_league_description: "Knockout\nRound-robin\nMulti-stage\nRound-robin-knockout\nDouble elimination",
    setup_league_description: "Provide regulations, images and location\nProvide team/member data\nInvite managers\nSetup fixture\nConfig phases",
    operate_league_description: "Active\nUpdate results\nView statistics\nShare with friends",
    league_operation: "League operation",
    league_operation_detail: "There are 3 phases of a league operation",
    multiple_league_support_title: "Multiple league formats are supported",
    multiple_league_support_description: "MyLeague supports users creating the leagues\nwhich have similar formats to the most popular leagues in the world such as Premier League, Champions League, World Cup.",
    knock_out: "Knock out",
    round_robin: "Round robin",
    winner_bracket_loser_bracket: "Winnerss Bracket - Losers Bracket",
    robin_phase_knockout: "Robin phase - knockout",
    group_stage: "Group stage",
};