export default {
    home: 'Home',
    nav_tournament: "Leagues",
    nav_team: 'Team',
    nav_pricing: "Price list",
    nav_blog: "Blog",
    nav_shopping: "Shops",
    nav_login: "Login",
    nav_register: "Register",
    nav_create_tournament: "Create league",
    nav_find_tournament: "Find league",
    nav_create_team: "Create team",
    nav_find_team: "Find team",
    nav_create_lineup: "Create lineup",
    vn: "Vietnamese",
    gb: "England",
    nav_account_information: "Account information",
    nav_account_my_leagues: "My leagues",
    nav_account_my_teams: "My teams",
    nav_account_my_orders: "My orders",
    nav_account_logout: "Log out",
    notifications: "Notifications",
    make_tournament_system: "Make Tournamation System",
    terms_of_user: "Terms of user",
    privacy_policy: "Privacy policy",
    payment_policy: "Payment policy",
    information_security_policy: "Information security policy",
    comments_on_football_legend: "Comments on Football-Legend",
};