export default {
    home: 'Trang chủ',
    nav_tournament: "Giải đấu",
    nav_team: 'Đội thi đấu',
    nav_pricing: "Bảng giá",
    nav_blog: "Blog",
    nav_shopping: "Mua sắm",
    nav_login: "Đăng nhập",
    nav_register: "Đăng ký",
    nav_create_tournament: "Tạo giải đấu",
    nav_find_tournament: "Tìm giải đấu",
    nav_create_team: "Tạo đội",
    nav_find_team: "Tìm đội",
    nav_create_lineup: "Tạo đội hình",
    vn: "Việt Nam",
    gb: "Anh",
    nav_account_information: "Thông tin tài khoản",
    nav_account_my_leagues: "Quản lý giải đấu",
    nav_account_my_teams: "Quản lý đội",
    nav_account_my_orders: "Quản lý đơn hàng",
    nav_account_logout: "Đăng xuất",
    notifications: "Thông báo",
    make_tournament_system: "Nền tảng quản lý giải đấu, đội thi đấu",
    terms_of_user: "Điều khoản sử dụng",
    privacy_policy: "Chính sách bảo mật",
    payment_policy: "Chính sách thanh toán",
    contact: "Liên hệ",
    information_security_policy: "Chính sách bảo mật thông tin cá nhân",
    comments_on_football_legend: "Nhận xét về Football-Legend",
    company_name: "Công ty cổ phần Football-Legend",
    license: "© 2023 - Bản quyền thuộc về football-legend.vn\nĐã đăng ký bản quyền",
    community_page: "Cộng đồng Football-Legend",
    facebook_group: `Nhóm Facebook`,
    members: "thành viên",
    visit_group: "Truy cập nhóm",
    facebook_introduction: "Hãy tham gia cộng đồng Football-Legend để được hỗ trợ tốt nhất!",
    setup_league: "Tùy chỉnh giải đấu",
    operate_league: "Điều hành giải đấu",
    create_league_description: "Loại trực tiếp\nĐấu vòng tròn\nChia bảng đấu\nVòng tròn - loại trực tiếp\nNhánh thắng - nhánh thua",
    setup_league_description: "Nhập điều lệ, hình và địa điểm\nNhập thông tin của đội/vận động viên\nMời người tham gia\nLập lịch đấu\nTùy chỉnh giai đoạn",
    operate_league_description: "Kích hoạt\nCập nhật kết quả\nXem thống kê\nChia sẻ với bạn bè",
    league_operation: "Điều hành giải",
    league_operation_detail: "Có 3 giai đoạn để điều hành giải",
    multiple_league_support_title: "Multiple league formats are supported",
    multiple_league_support_description: "MyLeague supports users creating the leagues\nwhich have similar formats to the most popular leagues in the world such as Premier League, Champions League, World Cup.",
    knock_out: "Loại trực tiếp",
    round_robin: "Đấu vòng tròn",
    winner_bracket_loser_bracket: "Nhánh thắng - Nhánh thua",
    robin_phase_knockout: "Vòng tròn - Loại trực tiếp",
    group_stage: "Chia bảng đấu",
    knock_out_desc: "Loại trực tiếp hoặc knockout là loại giải đấu có đội thua ở mỗi trận đấu sẽ bị loại ngay khỏi giải đấu.",
    round_robin_desc: "Mỗi đội sẽ thi đấu với tất cả các đội còn lại. Cho phép tuỳ chỉnh điều lệ xếp hạng dễ dàng.",
    winner_bracket_loser_bracket_desc: "Là biến thể khác của thể thức đấu loại trực tiếp. Với thể thức này thì các đội bị thua sẽ tiếp tục được đấu với nhau ở một nhánh đấu được gọi là Nhánh Thua",
    robin_phase_knockout_desc: "Kết hợp hai giai đoạn vào một giải đấu, bao gồm giai đoạn một đấu vòng tròn và giai đoạn hai loại trực tiếp hoặc nhánh thắng - nhánh thua.",
    group_stage_desc: "Có hai giai đoạn đó là giai đoạn một chia thành nhiều bảng đấu và giai đoạn hai là loại trực tiếp hoặc nhánh thắng - nhánh thua.",
    social_label: "Sử dụng tài khoản mạng xã hội", // need to translate to english from here
    register_email_label: "Đăng ký với email",
    email_address: "Địa chỉ Email",
    password: "Mật khẩu",
    confirm_password: "Nhập lại mật khẩu",
    and:" và ",
    confirm_policy_desc_1: "Bằng cách nhấp vào Đăng ký, bạn cho biết rằng bạn đã đọc hiểu và đồng ý với ",
    confirm_policy_desc_2: " của chúng tôi.",
    confirm_had_account: "Bạn đã có tài khoản?"
};