export default {
    home: 'Trang chủ',
    nav_tournament: "Giải đấu",
    nav_team: 'Đội thi đấu',
    nav_pricing: "Bảng giá",
    nav_blog: "Blog",
    nav_shopping: "Mua sắm",
    nav_login: "Đăng nhập",
    nav_register: "Đăng ký",
    nav_create_tournament: "Tạo giải đấu",
    nav_find_tournament: "Tìm giải đấu",
    nav_create_team: "Tạo đội",
    nav_find_team: "Tìm đội",
    nav_create_lineup: "Tạo đội hình",
    vn: "Việt Nam",
    gb: "Anh",
    nav_account_information: "Thông tin tài khoản",
    nav_account_my_leagues: "Quản lý giải đấu",
    nav_account_my_teams: "Quản lý đội",
    nav_account_my_orders: "Quản lý đơn hàng",
    nav_account_logout: "Đăng xuất",
    notifications: "Thông báo",
    make_tournament_system: "Nền tảng quản lý giải đấu, đội thi đấu",
    terms_of_user: "Điều khoản sử dụng",
    privacy_policy: "Chính sách bảo mật",
    payment_policy: "Chính sách thanh toán",
    contact: "Liên hệ",
    information_security_policy: "Chính sách bảo mật thông tin cá nhân",
    comments_on_football_legend: "Nhận xét về Football-Legend",
    company_name: "Công ty cổ phần Football-Legend",
    license: "© 2023 - Bản quyền thuộc về football-legend.vn\nĐã đăng ký bản quyền",
    community_page: "Cộng đồng Football-Legend",
    facebook_group: `Nhóm Facebook`,
    members: "thành viên",
    visit_group: "Truy cập nhóm",
    facebook_introduction: "Hãy tham gia cộng đồng Football-Legend để được hỗ trợ tốt nhất!"
};