export default {
    home: 'Trang chủ',
    nav_tournament: "Giải đấu",
    nav_team: 'Đội thi đấu',
    nav_pricing: "Bảng giá",
    nav_blog: "Blog",
    nav_shopping: "Mua sắm",
    nav_login: "Đăng nhập",
    nav_register: "Đăng ký",
    nav_create_tournament: "Tạo giải đấu",
    nav_find_tournament: "Tìm giải đấu",
    nav_create_team: "Tạo đội",
    nav_find_team: "Tìm đội",
    nav_create_lineup: "Tạo đội hình",
    vn: "Việt Nam",
    gb: "Anh",
    nav_account_information: "Thông tin tài khoản",
    nav_account_my_leagues: "Quản lý giải đấu",
    nav_account_my_teams: "Quản lý đội",
    nav_account_my_orders: "Quản lý đơn hàng",
    nav_account_logout: "Đăng xuất",
    notifications: "Thông báo"
};