module.exports = Object.freeze({
    HOME_VIEW_NAME: 'home',
    PRICE_LIST_VIEW_NAME: 'price-list',
    BLOG_VIEW_NAME: 'blog',
    SHOPPING_VIEW_NAME: 'shopping',
    LOGIN_VIEW_NAME: 'login',
    CREATE_TOURNAMENT_VIEW_NAME: 'create-tournament',
    LEAGUE_VIEW_NAME: 'league',
    COMPETITOR_VIEW_NAME: 'competitor',
    COMPETITOR_CREATE_VIEW_NAME: 'create',
    LINEUP_VIEW_NAME: 'lineup',
    ACCOUNT_VIEW_NAME: 'account',
    ACCOUNT_PROFILE_VIEW_NAME: 'profile',
    ACCOUNT_MANAGE_TEAM_VIEW_NAME: 'manage-team',
    ACCOUNT_MANAGE_TOURNAMENT_VIEW_NAME: 'manage-tournament',
    ACCOUNT_MANAGE_ORDER_VIEW_NAME: 'manage-order',
    CONTACT_VIEW_NAME: 'contact-us',
    PRIVACY_POLICY_VIEW_NAME: 'privacy-policy',
    TERMS_OF_USER_VIEW_NAME: 'terms-of-user',
    POLICY_PROFILE_VIEW_NAME: 'policy-profile'
  })